language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  local_dir: 'build'
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
