language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
